### ISSUE TITLE
Feature: Add distance as an optional column

### ISSUE THREAD

**Issue by AsunaTsuki** [Blooym/Wholist#40]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

New feature

### Summary of the feature

Add option to show distance from player as a column.

### Why should this be added or changed?

it would be nice to be able to see how far away you are from the target without having to right click open position on map

**Comment by Blooym** [comment]
This is definitely doable but not with the current setup the plugin uses as the data would only be updated every ~5 seconds at most and would be pretty inconsistent. If/when I rewrite the plugin I'll likely add this as a feature.

**Comment by Blooym** [comment]
Added in 3bc3d5c55112accbfa261e82fba88762e868221c

**Comment by AsunaTsuki** [comment]
Thank you!!
