### ISSUE TITLE
Feature: Add integration with Splatoon

### ISSUE THREAD

**Issue by AsunaTsuki** [Blooym/Wholist#41]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

New feature

### Summary of the feature

Add integration with splatoon as a way to left click on a person and have it draw a line to the player

### Why should this be added or changed?

it would be very useful to be able to left click on a player in the list and have it draw a line directly to them.

**Comment by Blooym** [comment]
I wouldn't be comfortable with developing an integration with a plugin that allows for borderline cheating. I also would likely not be allowed to do this even if I wanted due to strict 1st-party repository rules.
