### ISSUE TITLE
Bug: Columns to display randomly resets

### ISSUE THREAD

**Issue by AsunaTsuki** [Blooym/Wholist#42]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit my report.

### Bug Behavior

I noticed that sometimes when i switch worlds or zones, the columns i have selected get reset and i have to uncheck them again to make it the way I want.

### Expected Behavior

Columns displayed setting should be persistent

**Comment by Blooym** [comment]
This kind of information should be stored in `dalamudUI.ini` since I don't actually handle which columns should be selected/deselected myself, so I'm not sure what would be causing any kind of column setting to be reset.

**Comment by Blooym** [comment]
Confirmed resolved via another platform, closing this
