### ISSUE TITLE
Feature: more player info

### ISSUE THREAD

**Issue by K0shachiyamyatA** [Blooym/Wholist#48]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit.

### New or Existing?

Improvement to existing feature

### Summary of the feature

Options to show player's race and gender

### Why should this be added or changed?

Useful for FC recruiting, for example

**Comment by Blooym** [comment]
I won't be adding the ability to show/filter by race or gender as I think it's unnecessary information, I'm also not entirely sure how it can be used for things like FC recruitment. I'm also very cautious around data like this after the drama around OopsAllLalafels
