### ISSUE TITLE
Player count removed feature

### ISSUE THREAD

**Issue by Mageee** [Blooym/Wholist#51]
There used to be a number at the bottom of the ui that just displayed how many players were in the list. Don't remember exactly when this changed, maybe with dawntrail? I found myself referencing that number in a variety of situations, would be really nice if it was able to be brought back.

**Comment by Petra105** [comment]
Even though it caps at the render limit I found this feature helpful esp when getting a headcount for venues.

**Comment by Blooym** [comment]
Readded
